### ISSUE TITLE
Using JRuby: gem needs to be updated for 1.1.4

### ISSUE THREAD

**Issue by PfrLisBerndt** [RaiMan/SikuliX1#107]
Hello!
The current version of sikulixapi.jar does not start:

> NameError: missing class name (`org.sikuli.script.ScreenUnion')
    method_missing at org/jruby/javasupport/JavaPackage.java:252

Greetings!

**Comment by RaiMan** [comment]
should be fixed with build #262

**Comment by PfrLisBerndt** [comment]
In current build the failure still exists... @RaiMan

**Comment by RaiMan** [comment]
Sorry did not test :-(

... but should work now.

**Comment by PfrLisBerndt** [comment]
It is still not working...
perhaps I am doing wrong? But my sikulixapi.jar downloaded 09/2018 works fine...

**Comment by RaiMan** [comment]
You must use the latest build ( 2019-04-03_08:08 (Build 266))

> It is still not working...

... and exactly what?

**Comment by PfrLisBerndt** [comment]
I definitely use the current build. It´s the same failure as mentioned above...

**Comment by RaiMan** [comment]
Again made a test with the latest build downloaded from the Downloadpage on Windows 10 now.
Works.

**Comment by PfrLisBerndt** [comment]
Well, it´s significant; when I change my the older sikulixapi against that from build 266 from https://raiman.github.io/SikuliX1/sikulixapi.jar, only then the failure occurs. After rechange, my system works properly again.

> NameError: missing class name (`org.sikuli.script.ScreenUnion')
    method_missing at org/jruby/javasupport/JavaPackage.java:252
  <module:Sikulix> at C:/jruby-9.2.5.0/lib/ruby/gems/shared/gems/sikulix-1.1.0.3/lib/sikulix/sikulix.rb:16
            <main> at C:/jruby-9.2.5.0/lib/ruby/gems/shared/gems/sikulix-1.1.0.3/lib/sikulix/sikulix.rb:7
           require at org/jruby/RubyKernel.java:983
            (root) at C:/jruby-9.2.5.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
            <main> at C:/jruby-9.2.5.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:59
           require at org/jruby/RubyKernel.java:983
            <main> at C:/jruby-9.2.5.0/lib/ruby/gems/shared/gems/sikulix-1.1.0.3/lib/sikulix.rb:4
            <main> at C:/jruby-9.2.5.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
           require at org/jruby/RubyKernel.java:983
           require at C:/jruby-9.2.5.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:135
            <main> at C:/Ruby-TF/Actionperformer/UI_interactors/sikulix.rb:1
           require at org/jruby/RubyKernel.java:983
            (root) at uri:classloader:/jruby/kernel/kernel.rb:1

**Comment by RaiMan** [comment]
Sorry, but this is not supported by me.
.../gems/sikulix-1.1.0.3/lib/sikulix/sikulix.rb:16

Apparently this is not compatible with version 1.1.4.

**Comment by RaiMan** [comment]
Some classes like ScreenUnion are moved away from the top level, since they are not part of the official API.

This is reflected now in the actual version of sikulix.rb, but of course not in the gem, which is at level 1.1.0.

The actual sikulix.rb can be found in the app-data folder Sikulix/Lib.

**Comment by PfrLisBerndt** [comment]
Hmm, what a pity...
Do you know if there will be a gem-update in the next time?

**Comment by RaiMan** [comment]
Not possible to fix it locally?

gem-update: currently not my priority. But I put it on the list for the next days, to find out, what has to be done

**Comment by PfrLisBerndt** [comment]
I simply tried to replace the sikulix.rb´s, but then I get null-exceptions. I´m yet not that experienced in programming to fix it just that easily.

I would really appreciate that, to hold my framework up to date long-term.

**Comment by RaiMan** [comment]
ok, accepted.

I realised, that I am indeed responsible for the gem (last contact 5 years ago ;-).

So I will upload a new gem version asap and integrate it again into my routines.

**Comment by PfrLisBerndt** [comment]
*thumbs up*

**Comment by RaiMan** [comment]
before uploading the revised gem, I would like to have it tested.

Could you do the following:
- [download the gem from here](https://github.com/RaiMan/SikuliX1/raw/master/API/src/main/resources/Support/Ruby/sikulix-1.1.4.0/sikulix-1.1.4.0.gem)
- put it in an empty folder
- on a command line go into that folder
- run ``gem install sikulix``

This should install a sikulix gem with version 1.1.4.0.

Highly appreciated if you could test it.

**Comment by RaiMan** [comment]
Sorry, not yet working. I will give you a note.

**Comment by RaiMan** [comment]
ok, now you should be able to test

**Comment by PfrLisBerndt** [comment]
Installation succeeded, first tests, too. - Image recognizing, ocr, screenshots working as before.  Thanks for your work!

**Comment by RaiMan** [comment]
ok, thanks.
I will publish the gem tomorrow.
Could you then check again the next days with the published stuff

**Comment by RaiMan** [comment]
I have just pushed it.
